### ISSUE TITLE
Breaking issue in your code 🚨

### ISSUE THREAD

**Issue by mubaarakhassan** [maarten551/advent-of-code-2019#1]
I would like to say that your code looks nice, but there is one issue. You have only completed the advent of code challenge 2019 up to day 4! 

Aren't there 25 days? Also could you do the challenge in another language like C# :)

**Comment by maarten551** [comment]
Hey @mubaarakhassan, 

Thanks for showing interest in my code.

You're completely right that I haven't finished all 25 days, because why? Because I lost interest :(.
If you are at day 5, let me know. Maybe I will continue my quest of completing more days.

And for using C# as AoC language, I actually did back in 2017 (it even finished way more days).
You can find it here: https://github.com/maarten551/advent-of-code-2017
